export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const DOCTOR_LOGIN = 'DOCTOR_LOGIN';
export const DOCTOR_LOGOUT = 'DOCTOR_LOGOUT';
export const DOCTOR_LOGIN_SUCCESSFUL = 'DOCTOR_LOGIN_SUCCESSFUL';

export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';

export const FORGOT_PASSWORD_SET_STEP = 'FORGOT_PASSWORD_SET_STEP';
export const FORGOT_PASSWORD_SEND_PHONE = 'FORGOT_PASSWORD_SEND_PHONE';
export const FORGOT_PASSWORD_SEND_PHONE_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_PHONE_SUCCESSFUL';
export const FORGOT_PASSWORD_SEND_OTP = 'FORGOT_PASSWORD_SEND_OTP';
export const FORGOT_PASSWORD_SEND_OTP_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_OTP_SUCCESSFUL';
export const FORGOT_PASSWORD_CANCEL_REQUEST = 'FORGOT_PASSWORD_CANCEL_REQUEST';
export const FORGOT_PASSWORD_CANCEL_REQUEST_SUCCESSFUL = 'FORGOT_PASSWORD_CANCEL_REQUEST_SUCCESSFUL';
export const FORGOT_PASSWORD_RESET_PASSWORD = 'FORGOT_PASSWORD_RESET_PASSWORD';
export const FORGOT_PASSWORD_RESET_PASSWORD_SUCCESSFUL = 'FORGOT_PASSWORD_RESET_PASSWORD_SUCCESSFUL';

export const RESET_STEP_REGISTER = 'RESET_STEP_REGISTER';
export const GUEST_SEND_PHONE = 'GUEST_SEND_PHONE';
export const GUEST_SEND_PHONE_SUCCESSFUL = 'GUEST_SEND_PHONE_SUCCESSFUL';
export const GUEST_SEND_OTP = 'GUEST_SEND_OTP';
export const GUEST_SEND_OTP_SUCCESSFUL = 'GUEST_SEND_OTP_SUCCESSFUL';
export const GUEST_REGISTER = 'GUEST_REGISTER';
export const GUEST_REGISTER_SUCCESSFUL = 'GUEST_REGISTER_SUCCESSFUL';
