export const GET_SERVICE_FOR_HOME = 'GET_SERVICE_FOR_HOME';
export const SAVE_SERVICE_FOR_HOME = 'SAVE_SERVICE_FOR_HOME';
export const QUERY_SERVICE = 'QUERY_SERVICE';
export const QUERY_SERVICE_SUCCESSFUL = 'QUERY_SERVICE_SUCCESSFUL';
export const NEXT_QUERY_SERVICE = 'NEXT_QUERY_SERVICE';
export const NEXT_QUERY_SERVICE_SUCCESSFUL = 'NEXT_QUERY_SERVICE_SUCCESSFUL';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESSFUL = 'GET_ALL_CATEGORIES_SUCCESSFUL';
