export const GET_CHAT = 'GET_CHAT'
export const GET_CHAT_SUCCESSFUL = 'GET_CHAT_SUCCESSFUL'
export const GET_MORE_CHAT = 'GET_MORE_CHAT'
export const GET_MORE_CHAT_SUCCESSFUL = 'GET_MORE_CHAT_SUCCESSFUL'