export const SET_RINGTONE = "SET_RINGTONE";

export const SET_CALL_STATUS = "SET_CALL_STATUS";
export const SET_OPEN_VIDEOCALL = "SET_OPEN_VIDEOCALL";
export const SET_OPPONENT_DATA = "SET_OPPONENT_DATA";
