

export const GET_PACKAGE_INFO = "GET_PACKAGE_INFO";
export const GET_PACKAGE_INFO_SUCCESSFUL = "GET_PACKAGE_INFO_SUCCESSFUL";

export const GET_PACKAGE_SERVICES = "GET_PACKAGE_SERVICES";
export const GET_PACKAGE_SERVICES_SUCCESSFUL = "GET_PACKAGE_SERVICES_SUCCESSFUL";

export const GET_PACKAGE_APPOINTMENTS = "GET_PACKAGE_APPOINTMENTS";
export const GET_PACKAGE_APPOINTMENTS_SUCCESSFUL = "GET_PACKAGE_APPOINTMENTs_SUCCESSFUL";

export const GET_PACKAGE_STATUS = "GET_PACKAGE_STATUS";
export const GET_PACKAGE_STATUS_SUCCESSFUL = "GET_PACKAGE_STATUS_SUCCESSFUL";

export const CHANGE_PACKAGE_STATUS = "CHANGE_PACKAGE_STATUS";


export const UPDATE_PACKAGE = "UPDATE_PACKAGE";

export const UPDATE_APPOINTMENT_PACKAGE = "UPDATE_APPOINTMENT_PACKAGE";

export const GET_ALL_APPOINTMENT = "GET_ALL_APPOINTMENT";
export const GET_ALL_APPOINTMENT_SUCCESSFUL = "GET_ALL_APPOINTMENT_SUCCESSFUL";
export const RATING_DOCTOR = "RATING_DOCTOR";
export const UPDATE_RATING_DOCTOR = "UPDATE_RATING_DOCTOR";
