export const GET_USER = 'GET_USER';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const GET_USER_SUCCESSFUL = 'GET_USER_SUCCESSFUL';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESSFUL = 'GET_USER_PROFILE_SUCCESSFUL';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const EDIT_AVATAR = 'EDIT_AVATAR';
export const EDIT_USER_PROFILE_SUCCESSFUL = 'EDIT_USER_PROFILE_SUCCESSFUL';
export const RESET_UPLOAD_STATUS = 'RESET_UPLOAD_STATUS';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESSFUL = 'CHANGE_PASSWORD_SUCCESSFUL';

export const CHANGE_PHONE_VERIFY = 'CHANGE_PHONE_VERIFY';
export const CHANGE_PHONE_VERIFY_SUCCESSFUL = 'CHANGE_PHONE_VERIFY_SUCCESSFUL';
export const CHANGE_PHONE_CANCEL = 'CHANGE_PHONE_CANCEL';
export const CHANGE_PHONE_CANCEL_SUCCESSFUL = 'CHANGE_PHONE_CANCEL_SUCCESSFUL';
export const CHANGE_PHONE = 'CHANGE_PHONE';
export const CHANGE_PHONE_SUCCESSFUL = 'CHANGE_PHONE_SUCCESSFUL';

export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_SUCCESSFUL = 'CHANGE_EMAIL_SUCCESSFUL';

export const RESET_SETTING_STATUS = 'RESET_SETTING_STATUS';

export const GET_PATIENT = 'GET_PATIENT';
export const GET_PATIENT_SUCCESSFUL = 'GET_PATIENT_SUCCESSFUL';

export const GET_USER_PACKAGE = 'GET_USER_PACKAGE';
export const GET_USER_PACKAGE_SUCCESSFUL = 'GET_USER_PACKAGE_SUCCESSFUL';


