export const GET_ALL_DEPENDENT = 'GET_ALL_DEPENDENT';       //get all Patient by CustomerID
export const GET_ALL_DEPENDENT_SUCCESSFUL = 'GET_ALL_DEPENDENT_SUCCESSFUL';
export const CREATE_DEPENDENT = 'CREATE_DEPENDENT';
export const CREATE_DEPENDENT_SUCCESSFUL = 'CREATE_DEPENDENT_SUCCESSFUL';

export const GET_PACKAGE_PROGRESS = 'GET_PACKAGE_PROGRESS';
export const GET_PACKAGE_PROGRESS_SUCCESSFUL = 'GET_PACKAGE_PROGRESS_SUCCESSFUL';